export { construct,
         constructArray,
         createApiData,
         updateApiData,
         deleteApiData,
         genInstance } from './options';

export { api,
         query,
         id,
         cacheable,
         secure,
         create,
         access,
         accessQuery,
         isSecure,
         isCacheable,
         getName,
         accessId,
         getBaseUrl,
         accessFilter,
         config,
         key,
         isPrimitive } from './util';